pipeline {
   agent any
    environment {
      RELEASE='20.04'
    }
   stages {
      stage('Build') {
            environment {
               LOG_LEVEL='INFO'
            }
            steps {
               echo "Building release ${RELEASE} with log level ${LOG_LEVEL}..."
               sh 'chmod +x 02/demos/demo3/build.sh'
               withCredentials([string(credentialsId: 'slack_token', variable: 'API_KEY')]) {
                  sh '''
                     ./02/demos/demo3/build.sh
                  '''
               }
            }
        }
        stage('Test') {
            steps {
               script {
                  if(Math.random() > 0.5){
                     throw new Exception()
                  }
               }
               echo "Testing release ${RELEASE}"
               writeFile file: 'test-results.txt', text: 'passed'               
            }
        }
   }
   post {
      success {
         archiveArtifacts 'test-results.txt'
         slackSend channel: '#builds',
                   color: 'good',
                   message: "Release ${env.RELEASE}, success: ${currentBuild.fullDisplayName}."
         slackSend channel: '#builds',
                   color: 'danger',
                   message: "Release ${env.RELEASE}, failure: ${currentBuild.fullDisplayName}."
      }
   }
}
